"""aritmetika_db table

Revision ID: 5e7a3da5a3ef
Revises: 
Create Date: 2021-08-11 13:43:22.351211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7a3da5a3ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aritmetika_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nilai_1', sa.Integer(), nullable=True),
    sa.Column('nilai_2', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=5), nullable=True),
    sa.Column('hasil', sa.Integer(), nullable=True),
    sa.Column('ket', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aritmetika_db')
    # ### end Alembic commands ###
